### ISSUE TITLE
[help] Does it work well with multiple graphs?

### ISSUE THREAD

**Issue by e-zz** [luckykellan/logseq-plugin-ticktick#4]
Hi, I use two graphs on a daily basis and create a lot of TODOs in both. So before the synchronisation, how is it decided which graph the task should go to? 
Or say, is there any plan to support multiple graphs? Thanks!

**Comment by luckykellan** [comment]
Thank you for reaching out with your question. Currently, there are no plans to support multiple graphs, primarily because I do not use multiple graphs myself. This makes it challenging to consider and implement features tailored to multi-graph scenarios. I apologize for any inconvenience this may cause and appreciate your understanding.

**Comment by e-zz** [comment]
Thanks for the plugin and your quick reply to my question. No worries, I understand it's not a small change and takes a lot of time. It's already quite nice that we could have your plugin!
